#!/usr/bin/env python3
"""
Regional Distribution Operations Platform - Synthetic Seed Data Generator
Generates application/seed.sql with fake warehouses, products, inventory,
customers, orders, order items, and shipments for demo/testing purposes.

Usage: python3 scripts/generate_seed_data.py
Output: application/seed.sql (overwritten)

All data is synthetic. No real customer or business information is used.
"""

import random
from datetime import date, timedelta
from pathlib import Path

random.seed(42)  # reproducible output

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "application" / "seed.sql"

WAREHOUSES = [
    ("Atlanta North", "Atlanta, GA"),
    ("Savannah Port", "Savannah, GA"),
    ("Macon Central", "Macon, GA"),
]

# (sku, name, category, unit_price)
PRODUCTS = [
    ("WH-10001", "Wireless Scanner", "Electronics", 249.99),
    ("WH-10002", "Pallet Jack", "Warehouse Equipment", 425.00),
    ("WH-10003", "Cardboard Box (Medium)", "Packaging", 0.85),
    ("WH-10004", "Cardboard Box (Large)", "Packaging", 1.25),
    ("WH-10005", "Packing Tape Roll", "Packaging", 3.50),
    ("WH-10006", "Safety Vest", "Safety", 12.99),
    ("WH-10007", "Steel Shelving Unit", "Warehouse Equipment", 189.00),
    ("WH-10008", "Forklift Battery", "Warehouse Equipment", 650.00),
    ("WH-10009", "Barcode Label Roll", "Packaging", 8.75),
    ("WH-10010", "Hand Truck", "Warehouse Equipment", 95.00),
    ("WH-10011", "Bubble Wrap Roll", "Packaging", 22.50),
    ("WH-10012", "Work Gloves", "Safety", 6.25),
    ("WH-10013", "Stretch Wrap Film", "Packaging", 18.00),
    ("WH-10014", "Warehouse Fan", "Facilities", 145.00),
    ("WH-10015", "LED Work Light", "Facilities", 34.99),
    ("WH-10016", "Storage Tote Bin", "Warehouse Equipment", 14.50),
    ("WH-10017", "Conveyor Roller", "Warehouse Equipment", 62.00),
    ("WH-10018", "Pallet (Wood)", "Packaging", 11.00),
    ("WH-10019", "Fire Extinguisher", "Safety", 55.00),
    ("WH-10020", "First Aid Kit", "Safety", 28.50),
    ("WH-10021", "Handheld Label Printer", "Electronics", 175.00),
    ("WH-10022", "Inventory Tablet", "Electronics", 320.00),
    ("WH-10023", "Loading Dock Plate", "Warehouse Equipment", 210.00),
    ("WH-10024", "Security Camera", "Electronics", 89.99),
    ("WH-10025", "Break Room Chair", "Facilities", 74.99),
]

# Customers are synthetic B2B accounts (not real companies/people).
CUSTOMER_PREFIXES = [
    "Peachtree", "Coastal", "Piedmont", "Magnolia", "Ironhorse", "Summit",
    "Riverside", "Blue Ridge", "Southern Cross", "Kudzu", "Redstone",
    "Colonial", "Harborview", "Pinecrest", "Cornerstone", "Highland",
    "Lakeside", "Palmetto", "Granite", "Cedar Creek", "Meridian",
    "Golden Gate", "Union", "Crescent", "Falcon", "Trailhead", "Anchor",
    "Sunbelt", "Evergreen", "Northgate",
]
CUSTOMER_SUFFIXES = ["Supply Co.", "Distribution LLC", "Hardware Inc.", "Logistics Group", "Trading Co.", "Wholesale Partners"]
CITIES = [
    ("Atlanta", "GA"), ("Savannah", "GA"), ("Macon", "GA"), ("Augusta", "GA"),
    ("Columbus", "GA"), ("Athens", "GA"), ("Charlotte", "NC"), ("Jacksonville", "FL"),
    ("Nashville", "TN"), ("Birmingham", "AL"), ("Charleston", "SC"), ("Tampa", "FL"),
]

CARRIERS = ["FreightLine Express", "SouthEast Haulers", "Regional Trucking Co.", "SwiftShip Logistics"]

ORDER_STATUS_WEIGHTS = [
    ("Pending", 6), ("Processing", 8), ("Ready to Ship", 6),
    ("Shipped", 12), ("Completed", 14), ("Cancelled", 4),
]

TODAY = date(2026, 9, 2)


def sql_str(value):
    return "'" + str(value).replace("'", "''") + "'"


def build_status_list():
    statuses = []
    for status, count in ORDER_STATUS_WEIGHTS:
        statuses.extend([status] * count)
    random.shuffle(statuses)
    return statuses


def main():
    lines = []
    lines.append("-- Regional Distribution Operations Platform - Synthetic Seed Data")
    lines.append("-- Generated by scripts/generate_seed_data.py -- synthetic data only, no real records.")
    lines.append("")
    lines.append("SET FOREIGN_KEY_CHECKS = 0;")
    lines.append("TRUNCATE TABLE shipments;")
    lines.append("TRUNCATE TABLE order_items;")
    lines.append("TRUNCATE TABLE orders;")
    lines.append("TRUNCATE TABLE inventory;")
    lines.append("TRUNCATE TABLE customers;")
    lines.append("TRUNCATE TABLE products;")
    lines.append("TRUNCATE TABLE warehouses;")
    lines.append("SET FOREIGN_KEY_CHECKS = 1;")
    lines.append("")

    # Warehouses
    lines.append("-- Warehouses")
    lines.append("INSERT INTO warehouses (warehouse_id, name, location) VALUES")
    rows = [f"({i+1}, {sql_str(name)}, {sql_str(loc)})" for i, (name, loc) in enumerate(WAREHOUSES)]
    lines.append(",\n".join(rows) + ";")
    lines.append("")

    # Products
    lines.append("-- Products")
    lines.append("INSERT INTO products (product_id, sku, name, category, unit_price) VALUES")
    rows = [
        f"({i+1}, {sql_str(sku)}, {sql_str(name)}, {sql_str(cat)}, {price:.2f})"
        for i, (sku, name, cat, price) in enumerate(PRODUCTS)
    ]
    lines.append(",\n".join(rows) + ";")
    lines.append("")

    # Inventory: every product in every warehouse, with a handful pushed to low/zero stock
    lines.append("-- Inventory (per product per warehouse)")
    lines.append("INSERT INTO inventory (product_id, warehouse_id, quantity_available, quantity_reserved, reorder_level) VALUES")
    inv_rows = []
    low_stock_indexes = set(random.sample(range(len(PRODUCTS) * len(WAREHOUSES)), 10))
    idx = 0
    for p_idx, _ in enumerate(PRODUCTS):
        for w_idx, _ in enumerate(WAREHOUSES):
            reorder_level = random.choice([20, 30, 50, 75])
            if idx in low_stock_indexes:
                available = random.randint(0, reorder_level - 1)
            else:
                available = random.randint(reorder_level + 10, reorder_level + 250)
            reserved = random.randint(0, min(available, 40))
            inv_rows.append(f"({p_idx+1}, {w_idx+1}, {available}, {reserved}, {reorder_level})")
            idx += 1
    lines.append(",\n".join(inv_rows) + ";")
    lines.append("")

    # Customers
    lines.append("-- Customers (synthetic accounts)")
    lines.append("INSERT INTO customers (customer_id, name, email, phone, city, state) VALUES")
    cust_rows = []
    used_names = set()
    customers = []
    while len(customers) < 30:
        prefix = random.choice(CUSTOMER_PREFIXES)
        suffix = random.choice(CUSTOMER_SUFFIXES)
        name = f"{prefix} {suffix}"
        if name in used_names:
            continue
        used_names.add(name)
        customers.append(name)
    for i, name in enumerate(customers):
        city, state = random.choice(CITIES)
        slug = name.lower().replace(" ", "").replace(".", "").replace(",", "")[:20]
        email = f"orders@{slug}.example.com"
        phone = f"({random.randint(200,999)}) 555-{random.randint(1000,9999)}"
        cust_rows.append(f"({i+1}, {sql_str(name)}, {sql_str(email)}, {sql_str(phone)}, {sql_str(city)}, {sql_str(state)})")
    lines.append(",\n".join(cust_rows) + ";")
    lines.append("")

    # Orders
    num_orders = 50
    statuses = build_status_list()
    order_dates = []
    for i in range(num_orders):
        days_ago = random.randint(0, 45)
        order_dates.append(TODAY - timedelta(days=days_ago))

    lines.append("-- Orders")
    lines.append("INSERT INTO orders (order_id, order_number, customer_id, order_date, status) VALUES")
    order_rows = []
    for i in range(num_orders):
        order_id = i + 1
        order_number = f"ORD-{100000 + order_id}"
        customer_id = random.randint(1, 30)
        order_rows.append(
            f"({order_id}, {sql_str(order_number)}, {customer_id}, {sql_str(order_dates[i].isoformat())}, {sql_str(statuses[i])})"
        )
    lines.append(",\n".join(order_rows) + ";")
    lines.append("")

    # Order items
    lines.append("-- Order Items")
    lines.append("INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES")
    item_rows = []
    for i in range(num_orders):
        order_id = i + 1
        num_items = random.randint(1, 3)
        chosen_products = random.sample(range(len(PRODUCTS)), num_items)
        for p_idx in chosen_products:
            sku, name, cat, price = PRODUCTS[p_idx]
            qty = random.randint(1, 10)
            item_rows.append(f"({order_id}, {p_idx+1}, {qty}, {price:.2f})")
    lines.append(",\n".join(item_rows) + ";")
    lines.append("")

    # Shipments: only for orders that have progressed past Pending/Cancelled
    lines.append("-- Shipments")
    lines.append("INSERT INTO shipments (shipment_number, order_id, warehouse_id, carrier, tracking_number, status, expected_delivery_date, shipped_date) VALUES")
    shipment_rows = []
    shipment_seq = 1
    status_map = {
        "Ready to Ship": "Preparing",
        "Shipped": "Shipped",
        "Completed": "Delivered",
    }
    for i in range(num_orders):
        order_status = statuses[i]
        if order_status not in status_map:
            continue
        order_id = i + 1
        warehouse_id = random.randint(1, len(WAREHOUSES))
        carrier = random.choice(CARRIERS)
        tracking_number = f"TRK{random.randint(10**8, 10**9 - 1)}"
        ship_status = status_map[order_status]
        # occasionally mark an in-progress shipment as Delayed or In Transit for variety
        if ship_status == "Shipped" and random.random() < 0.3:
            ship_status = random.choice(["In Transit", "Delayed"])
        order_date = order_dates[i]
        shipped_date = order_date + timedelta(days=random.randint(1, 4))
        expected_delivery = shipped_date + timedelta(days=random.randint(2, 7))
        shipped_date_sql = "NULL" if ship_status == "Preparing" else sql_str(shipped_date.isoformat())
        shipment_number = f"SHP-{200000 + shipment_seq}"
        shipment_rows.append(
            f"({sql_str(shipment_number)}, {order_id}, {warehouse_id}, {sql_str(carrier)}, "
            f"{sql_str(tracking_number)}, {sql_str(ship_status)}, {sql_str(expected_delivery.isoformat())}, {shipped_date_sql})"
        )
        shipment_seq += 1
    lines.append(",\n".join(shipment_rows) + ";")
    lines.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH} ({len(lines)} lines)")
    print(f"Warehouses: {len(WAREHOUSES)} | Products: {len(PRODUCTS)} | Customers: {len(customers)} | Orders: {num_orders} | Shipments: {shipment_seq - 1}")


if __name__ == "__main__":
    main()
